project_name: ocm-backplane

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
      - "GO111MODULE=on"
      - "GOFLAGS=-mod=readonly -trimpath"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/ocm-backplane/
    binary: ocm-backplane

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: "openshift"
    name: "backplane-cli"
